# action.yml
name: "Splunk AppInspect"
description: "Run Splunk App insect on a Splunk app directory."
inputs:
  app_path:
    description: "path to the application directory to be inspected"
    default: build/splunkbase
  result_file:
    description: "json result file name"
    default: "appinspect_result.json"
  included_tags:
    description: "Tags to include"
    required: false
  excluded_tags:
    description: "Tags to exclude"
    required: false
  appinspect_manual_checks:
    description: "Path to app vetting yaml for manual checks"
    required: false
    default: ".appinspect.manualcheck"
  appinspect_expected_failures:
    description: "Path to app vetting yaml for expected appinspect failures"
    required: false
    default: ".appinspect.expect"
  manual_check_markdown:
    description: "Path to generated file with markdown for manual checks"
    required: false
    default: "manual_check_markdown.txt"
  expected_failure_markdown:
    description: "Path to generated file with markdown for exceptions"
    required: false
    default: "expected_failure_markdown.txt"
outputs:
  status:
    description: "value is success/fail based on app inspect result"
runs:
  using: "docker"
  image: "Dockerfile"
